Repository Linggo-App/linggo, pull requests merged in 2021-05, with the labels that each got.

#30 Melhorias página projetos.
  global.css
  src/css/add_quadros.css
  src/php/add_agenda.php
  src/php/perfil.php
Labels: Assets, bug, code, content, documentation

#31 Rel 20210502
  Documentacao/Relatorio/rel20210502.txt
  Documentacao/Video/LinkReuniao_20210502
Labels: documentation

#40 Feature/melhorias tela rotina 01
  src/css/rotina.css
  src/js/rotina.js
  src/php/rotina.php
Labels: code, content, design, feature, layout

#42 hotfix_1.0
  src/js/rotina.js
  src/php/rotina.php
Labels: hotfix

#43 php da página rotina
  src/css/add_quadros.css
  src/extras/conexao.inc
  src/js/rotina.js
  src/php/add_agenda.php
  src/php/cadastro.php
  src/php/header.php
  src/php/rotina.php
Labels: Assets, code, design, documentation

#46 feature/php_rotina
  src/js/rotina.js
  src/php/rotina.php
Labels: code, feature

#48 Hotfix/melhorias-paginas
  htaccess
  index.php
  src/css/rotina.css
  src/js/rotina.js
  src/php/add_agenda.php
  src/php/header.php
  src/php/rotina.php
Labels: code, design, hotfix, layout

#50 arrumando erros
  src/css/add_quadros.css
  src/php/add_agenda.php
  src/php/cadastro.php
  src/php/header.php
  src/php/rotina.php
Labels: bug

#51 Hotfix/concertos
  index.php
  src/php/add_agenda.php
  src/php/cadastro.php
  src/php/header.php
  src/php/perfil.php
  src/php/rotina.php
Labels: bug, hotfix

#55 Versionamento v0.1-beta
  .htaccess
  README.md
  assets/GitHub-Mark-64px.png
  assets/Linggo-Logo.png
  assets/Mini-Logo.png
  assets/master-assets/img/Initial.txt
  assets/master-assets/videos/Initial.txt
  global.css
  index.php
  src/css/Initial.txt
  src/css/add_quadros.css
  src/css/index.css
  src/css/register.css
  src/css/rotina.css
  src/extras/Initial.txt
  src/extras/linggo_db.sql
  src/html/Initial.txt
  src/js/Initial.txt
  src/js/arquivo.js
  src/js/footer.js
  src/js/jquery-3.5.1.min.js
  src/js/rotina.js
  src/js/valid.js
  src/php/Initial.txt
  src/php/add_agenda.php
  src/php/cadastro.php
  src/php/footer.php
  src/php/header.php
  src/php/perfil.php
  src/php/rotina.php
Labels: release

#57 Feature/melhorias footer 1.0
  assets/LingoApp_Branco_Cortada.png
  global.css
  index.php
Labels: Assets, design, feature, layout

#58 Feature/pagina-restaurar-rotinas
  index.php
  src/css/rotina.css
  src/js/restoreProject.js
  src/php/proj_disab.php
  src/php/rotina.php
Labels: Assets, code, design, feature, layout

#59 Rel 20210516
  Documentacao/Relatorio/rel20210516.txt
  Documentacao/Video/LinkReuniao_20210516.txt
Labels: documentation

#60 Alteração no texto do modal.
  src/css/rotina.css
  src/php/rotina.php
Labels: design

#61 pagina perfil
  global.css
  src/css/perfil.css
  src/extras/linggo.sql
  src/js/perfil.js
  src/php/cadastro.php
  src/php/perfil.php
Labels: Assets, code, design, documentation
