Repository Linggo-App/linggo, pull requests merged in 2021-06, with the labels that each got.

#62 Release v0.1-beta
  README.md
  assets/GitHub-Mark-64px.png
  assets/LingoApp_Branco.png
  assets/LingoApp_Branco_Cortada.png
  global.css
  index.php
  src/css/add_quadros.css
  src/css/perfil.css
  src/css/register.css
  src/css/rotina.css
  src/extras/linggo.sql
  src/js/perfil.js
  src/js/restoreProject.js
  src/php/add_agenda.php
  src/php/cadastro.php
  src/php/footer.php
  src/php/header.php
  src/php/perfil.php
  src/php/proj_disab.php
  src/php/rotina.php
Labels: release

#63 Feature/index
  assets/master-assets/img/prints/coluna_inicio.png
  assets/master-assets/img/prints/coluna_opt.png
  assets/master-assets/img/prints/criar_coluna.png
  assets/master-assets/img/prints/criar_tarefa.png
  assets/master-assets/img/prints/definindo_tarefa.png
  assets/master-assets/img/prints/delet_project.png
  assets/master-assets/img/prints/delet_tarefa.png
  assets/master-assets/img/prints/delete_column.png
  assets/master-assets/img/prints/invalid_user.png
  assets/master-assets/img/prints/login.png
  assets/master-assets/img/prints/pallet_color.png
  assets/master-assets/img/prints/projetos.png
  assets/master-assets/img/prints/registred.png
  assets/master-assets/img/prints/rename_column.png
  assets/master-assets/img/prints/rename_project.png
  assets/master-assets/img/prints/rename_tarefa.png
  assets/master-assets/img/prints/tarefa_criada.png
  assets/master-assets/img/prints/titulo_projeto.png
  assets/master-assets/img/prints/validando_user.png
  assets/master-assets/img/slide_img/cadastro/cadastro_login.jpeg
  assets/master-assets/img/slide_img/cadastro/cadastro_login_opt2.jpeg
  assets/master-assets/img/slide_img/cadastro/invalid_user.png
  assets/master-assets/img/slide_img/cadastro/login.png
  assets/master-assets/img/slide_img/cadastro/registred.png
  assets/master-assets/img/slide_img/cadastro/validando_user.jpeg
  assets/master-assets/img/slide_img/colunas/coluna_inicio.png
  assets/master-assets/img/slide_img/colunas/coluna_opt.png
  assets/master-assets/img/slide_img/colunas/criar_coluna.png
  assets/master-assets/img/slide_img/colunas/delete_column.png
  assets/master-assets/img/slide_img/colunas/rename_column.png
  assets/master-assets/img/slide_img/perfil/editar_perfil.png
  assets/master-assets/img/slide_img/perfil/entrando_na_pag.png
  assets/master-assets/img/slide_img/perfil/perfil_inicio.png
  assets/master-assets/img/slide_img/perfil/proj_delets.png
  assets/master-assets/img/slide_img/perfil/restore_proj.png
  assets/master-assets/img/slide_img/perfil/restore_proj2.png
  assets/master-assets/img/slide_img/perfil/salvando_senha.png
  assets/master-assets/img/slide_img/perfil/trocando_nome.png
  assets/master-assets/img/slide_img/projetos/delet_project.png
  assets/master-assets/img/slide_img/projetos/final.jpeg
  assets/master-assets/img/slide_img/projetos/pallet_color.png
  assets/master-assets/img/slide_img/projetos/projetos_inicio.png
  assets/master-assets/img/slide_img/projetos/rename_project.png
  assets/master-assets/img/slide_img/projetos/select_cores.jpeg
  assets/master-assets/img/slide_img/projetos/titulo_projeto.png
  assets/master-assets/img/slide_img/tarefas/criar_tarefa.png
  assets/master-assets/img/slide_img/tarefas/definindo_tarefa.png
  assets/master-assets/img/slide_img/tarefas/delet_tarefa.png
  assets/master-assets/img/slide_img/tarefas/edit_tarefa.png
  global.css
  index.php
  src/css/index.css
  src/css/perfil.css
  src/css/rotina.css
  src/js/index.js
  src/php/perfil.php
Labels: Assets, code, content, design

#64 Feature/suporte2
  global.css
  index.php
  src/css/index.css
  src/php/header.php
Labels: Assets, code, content
